services:
    app:
        restart: "no"
    postgres:
        restart: "no"
        volumes:
            - pgdata_test:/var/lib/postgresql/data
        ports:
            - ${POSTGRES_PORT}:5432
    redis:
        restart: "no"
        volumes:
            - redis_test:/data
        ports:
            - ${REDIS_PORT}:6379
    nginx:
        restart: "no"
        environment:
            - APP_LISTEN_PORT=${APP_PORT}
        ports:
            - ${APP_PORT}:${APP_PORT}
    tests_app:
        restart: "no"
        volumes:
            - ./src:/src

volumes:
    pgdata_test:
    redis_test:
