services:
    app:
        environment:
            - ENVIRONMENT=production
    postgres:
        volumes:
            - pgdata_prod:/var/lib/postgresql/data
    redis:
        volumes:
            - redis_prod:/data
    nginx:
        environment:
            - APP_LISTEN_PORT=${APP_PORT}
        ports:
            - ${APP_PORT}:${APP_PORT}
    jaeger:
        ports:
            - ${JAEGER_TCP_PORT}:16686
        volumes:
            - jaeger_prod:/badger

volumes:
    pgdata_prod:
    redis_prod:
    jaeger_prod:
