services:
    app:
        environment:
            - ENVIRONMENT=production
    postgres:
        volumes:
            - pgdata_prod:/var/lib/postgresql/data
    redis:
        volumes:
            - redis_prod:/data
    nginx:
        environment:
            - APP_LISTEN_PORT=${APP_PORT}
        ports:
            - ${APP_PORT}:${APP_PORT}

volumes:
    pgdata_prod:
    redis_prod:
