services:
    tests:
        platform: ${DOCKER_IMG_PLATFORM:-linux/amd64}
        build:
            context: .
            dockerfile: docker/tests/Dockerfile
            args:
                - img=${PYTHON_IMG}
        env_file: .env
        environment:
            APP_HOST: localhost
            APP_PORT: 5000
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432
            REDIS_HOST: redis
            REDIS_PORT: 6379
            JAEGER_HOST: jaeger
            JAEGER_UDP_PORT: 6831
        depends_on:
            postgres:
                condition: service_healthy
            redis:
                condition: service_started
        profiles:
            - tests

    postgres:
        volumes:
            - postgres_data_test:/var/lib/postgresql/data

    redis:
        volumes:
            - redis_data_test:/data

volumes:
    postgres_data_test:
    es_data_test:
    redis_data_test:
