x-base-dev-service: &base-dev-service
    restart: "no"

services:
    app:
        <<: *base-dev-service
        environment:
            - ENVIRONMENT=development
            - FLASK_DEBUG=1
        volumes:
            - ./src/movies_auth:/app/src/movies_auth

    postgres:
        <<: *base-dev-service
        ports:
            - ${POSTGRES_PORT}:5432

    redis:
        <<: *base-dev-service
        ports:
            - ${REDIS_PORT}:6379

    jaeger:
        <<: *base-dev-service
