services:
    app:
        restart: "no"
        environment:
            - ENVIRONMENT=development
        volumes:
            - ./src:/src
    postgres:
        restart: "no"
        volumes:
            - pgdata_dev:/var/lib/postgresql/data
        ports:
            - ${POSTGRES_PORT}:5432
    redis:
        restart: "no"
        volumes:
            - redis_dev:/data
        ports:
            - ${REDIS_PORT}:6379
    nginx:
        restart: "no"
        environment:
            - APP_LISTEN_PORT=${APP_PORT}
        ports:
            - ${APP_PORT}:${APP_PORT}
volumes:
    pgdata_dev:
    redis_dev:
