services:
    app:
        restart: "no"
    postgres:
        restart: "no"
        ports:
            - ${POSTGRES_PORT}:5432
    redis:
        restart: "no"
        ports:
            - ${REDIS_PORT}:6379
    nginx:
        restart: "no"
        environment:
            - APP_LISTEN_PORT=${APP_PORT}
        ports:
            - ${APP_PORT}:${APP_PORT}
    jaeger:
        restart: "no"
        ports:
            - ${JAEGER_TCP_PORT}:16686
    tests_app:
        restart: "no"
        volumes:
            - ./src:/src
