"""Add model EntryRecord

Revision ID: 6571c55d82fe
Revises: e61f4c465b95
Create Date: 2022-10-21 15:33:00.224076

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6571c55d82fe"
down_revision = "e61f4c465b95"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("entry_records", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("entry_records", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    # ### end Alembic commands ###
