"""Add is_superuser to User model

Revision ID: a359bce81fd1
Revises: 6571c55d82fe
Create Date: 2022-10-23 12:07:09.947095

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a359bce81fd1"
down_revision = "6571c55d82fe"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_superuser", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("is_superuser")

    # ### end Alembic commands ###
