"""Delete CASCADE permissions to User

Revision ID: b2705448171a
Revises: 14c1145e15eb
Create Date: 2022-10-25 10:40:58.354985

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b2705448171a"
down_revision = "14c1145e15eb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("entry_records_user_id_fkey", "entry_records", type_="foreignkey")
    op.create_foreign_key(None, "entry_records", "users", ["user_id"], ["id"], ondelete="CASCADE")
    op.create_unique_constraint(None, "permissions", ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "permissions", type_="unique")
    op.drop_constraint(None, "entry_records", type_="foreignkey")
    op.create_foreign_key(
        "entry_records_user_id_fkey", "entry_records", "users", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###
