"""Update

Revision ID: f98cdd7fa1ad
Revises: c60f12c3e034
Create Date: 2022-11-15 08:07:39.885437

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f98cdd7fa1ad"
down_revision = "c60f12c3e034"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "social_accounts", ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "social_accounts", type_="unique")
    # ### end Alembic commands ###
